'use client'
import { useCallback, useEffect, useState } from 'react'
import { SmsComposer, smsApi } from './SmsControls'
type History={quoteRequest?:{source:string;allowed:boolean;recorded_at:string;notice_version:string}|null;template:string;mobile:string|null;preference:{consent:boolean;opted_out:boolean}|null;jobs:Array<{id:string;status:string;reason:string|null;due_at:string;message:string;credits:number|null}>;replies:Array<{id:string;message:string;received_at:string;opted_out:boolean}>}
export default function QuoteSmsPanel({quoteRef}:{quoteRef:string}) {
  const [data,setData]=useState<History|null>(null),[error,setError]=useState(''),[evidence,setEvidence]=useState(''),[busy,setBusy]=useState(false)
  const load=useCallback(async()=>{try {const r=await fetch(`/api/staff/sms?view=quote&quoteRef=${encodeURIComponent(quoteRef)}`,{cache:'no-store'});const d=await r.json();if(!r.ok)throw new Error(d.error);setData(d);setError('')}catch(e){setError(e instanceof Error?e.message:'SMS history unavailable.')}},[quoteRef])
  useEffect(()=>{setData(null);void load()},[load])
  async function mutate(body:Record<string,unknown>) {setBusy(true);try{await smsApi({...body,quoteRef});setEvidence('');await load()}catch(e){setError(e instanceof Error?e.message:'SMS action failed.')}finally{setBusy(false)}}
  return <details className="rounded-2xl border border-gray-200 bg-white p-5" onToggle={e=>{if(e.currentTarget.open)void load()}}><summary className="cursor-pointer font-bold text-[#1a2744]">SMS reminders and replies</summary><div className="mt-4 space-y-4">
    <p className="text-sm text-gray-600">SMS status is separate from email delivery. Notifications follow successful online-estimate or final-quote email submission, not confirmed inbox delivery. Email resends do not create additional notifications. Quote-request permission covers the automatic quote notification only; custom manual SMS still needs recorded permission.</p>
    {error&&<p role="alert" className="text-sm text-amber-900">{error}</p>}
    {data&&<><p className="text-sm">Mobile: {data.mobile?`+${data.mobile}`:'No valid mobile'} - {data.preference?.opted_out?'Opted out':data.quoteRequest?.allowed===false?'Email only for this quote':data.quoteRequest?.allowed?'Quote request recorded':data.preference?.consent?'Permission recorded':'SMS permission needed'}</p>
    {data.quoteRequest&&<p className="text-sm text-gray-600">Request source: {data.quoteRequest.source==='online_request'?'Online customer':'Agent confirmation'}; recorded {new Date(data.quoteRequest.recorded_at).toLocaleString()}; notice {data.quoteRequest.notice_version}.</p>}
    <details><summary className="cursor-pointer text-sm font-semibold">Record SMS permission</summary><label className="mt-2 block text-sm">How and when permission was obtained or withdrawn<textarea className="mt-1 block w-full min-w-0 rounded-lg border border-gray-300 bg-white px-3 py-2.5 text-sm" value={evidence} onChange={e=>setEvidence(e.target.value)} maxLength={1000}/></label><div className="mt-2 flex flex-wrap gap-2"><button disabled={busy||!data.mobile||!!data.preference?.opted_out} className="rounded-lg border px-3 py-2 text-sm" onClick={()=>mutate({action:'preference',consent:true,evidence})}>Record permission</button><button disabled={busy||!data.mobile} className="rounded-lg border px-3 py-2 text-sm" onClick={()=>mutate({action:'preference',consent:false,evidence})}>Record opt-out</button></div></details>
    <details><summary className="cursor-pointer text-sm font-semibold">Send SMS manually</summary><div className="mt-3"><SmsComposer initialTemplate={data.template} quoteRef={quoteRef} onSent={()=>void load()}/></div></details>
    <div className="space-y-2"><h3 className="font-semibold">Delivery history</h3>{!data.jobs.length&&<p className="text-sm text-gray-500">No SMS scheduled for this quote.</p>}{data.jobs.map(job=><details key={job.id} className="rounded-lg border p-3 text-sm"><summary className="cursor-pointer">{job.status} - {new Date(job.due_at).toLocaleString('en-AU')}{job.reason?` - ${job.reason.replace(/_/g,' ')}`:''}</summary><p className="mt-2 whitespace-pre-wrap">{job.message||'Message will be rendered before sending.'}</p>{job.credits!==null&&<p>{job.credits} credits</p>}{['queued','leased'].includes(job.status)&&<button disabled={busy} className="mt-2 underline" onClick={()=>mutate({action:'cancel',id:job.id})}>Cancel reminder</button>}</details>)}</div>
    <div className="space-y-2"><h3 className="font-semibold">Replies</h3>{data.replies.map(r=><article key={r.id} className="rounded-lg bg-teal-50 p-3 text-sm"><p className="whitespace-pre-wrap">{r.message}</p><p className="mt-1 text-xs">{new Date(r.received_at).toLocaleString('en-AU')}{r.opted_out?' - Opted out':''}</p></article>)}{!data.replies.length&&<p className="text-sm text-gray-500">No replies received.</p>}</div></>}
  </div></details>
}
